src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Mauvais format de date")
     * @Assert\GreaterThan("today", message="Impossible de réserver pour ce jour !")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Mauvais format de date")
     * @Assert\GreaterThan(propertyPath="startDate", message="Impossible de réserver pour ce jour !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\PrePersist
     *
     * @return void
     */
    public function prePersist(){
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTime();
        }

        if(empty($this->amount)){
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    /**
     * Undocumented function
     *
     * @return array
     */
    public function isBookableDates(){
        $notAvailableDays = $this->ad->getNotAvailableDays();

        $bookingDays = $this->getDays();

        $formatDay = function($day){
            return $day->format('Y-m-d');
        };

        $days = array_map($formatDay, $bookingDays);
        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day ) {
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    public function getDays(){
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->startDate->getTimestamp(),
            24 * 60 * 80
        );

        $days = array_map(function($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getDuration(){
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{

    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer){
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration(" ", "01/01/2018" ))
            ->add('endDate', TextType::class, $this->getConfiguration(" ", "01/01/2018" ))
            ->add('comment', TextareaType::class,["required"=>false], $this->getConfiguration("Ajouter un commentaire", "Ecrivez votre commentaire"))
        ;

        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Form\BookingType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Common\Persistence\ObjectManager;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $user = $this->getUser();

            $booking->setBooker($user)
                ->setAd($ad)
                ;

            if (!$booking->isBookableDates()){
                $this->addFlash('warning',"Les dates que vous avez choisi ne peuvent être réservées");
            }else{
                $manager->persist($booking);
                $manager->flush();
    
                return $this->redirectToRoute('booking_show', ['id' => $booking->getId()]);
            }
        }

        return $this->render('booking/book.html.twig', [
           'ad' => $ad,
           'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     * @return Response
     */
    public function show(Booking $booking){
        return $this->render('booking/show.html.twig', [
            'booking' => $booking
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookingController!{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css
">
{% endblock %}
{% block body %}

<div class="container">

    <div class="booking-stage">
            <span class="overlay2"></span>
            <span class="overlay"></span>
        <img src="https://images.pexels.com/photos/239520/pexels-photo-239520.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt="">
        <div class="content-booking-stage pt-3">
            <h2>Réservez votre logement</h2>
            {{form_start(form)}}
                <div class="row mb-4 mt-5">
                    <div class="col-4"></div>
                    <div class="col-4">
                        <div class="row">
                            <div class="col-6 text-center h5">Date Entrée</div>
                            <div class="col-6 text-center h5">Date Sortie</div>
                        </div>
                        
                    </div>
                    <div class="col-4"></div>
                </div>
                <div class="row ">
                    <div class="col-4"></div>
                    <div class="col-4 date-booking">
                        <div class="row no-gutters">
                            <div class="col-6 start-date-booking">{{ form_row(form.startDate) }}</div>
                            <div class="col-6 end-date-booking"> {{ form_row(form.endDate) }}</div>
                        </div>
                        
                    </div>
                    <div class="col-4"></div>
                </div>
                <div class="row">
                    <div class="col-4"></div>
                    <div class="col-4 text-center">
                        <p class="mt-4 h5">Montant du séjour : <strong><span id="amount">...</span> &euro;</strong></p>
                        <p><strong><span id="days">0</span></strong>    nuit(s) à <strong>{{ad.price}} &euro;</strong> / nuits</p>
                    </div>
                    <div class="col-4"></div>
                </div>
                <div class="row">
                    <div class="col-4"></div>
                    <div class="col-4 text-center mt-2 comment-booking">
                        {{ form_row(form.comment) }}
                        <button type="submit" class="btn-booking-stage">Je réserve</button>
                    </div>
                    <div class="col-4"></div>
                </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

<script>
    $(document).ready(function(){
        
        $('#booking_startDate, #booking_endDate').datepicker({
            format: 'dd/mm/yyyy',
            datesDisabled : [
                {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                {% endfor %}
            ],
            startDate: new Date()
        });

        $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
    });

    function calculateAmount(){
        const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
        const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

        if(startDate && endDate && startDate < endDate){

            const interval = endDate.getTime() - startDate.getTime();
            const days = interval / (24 * 60 * 60 *1000);
            const amount = days * {{ ad.price }}

            $('#days').text(days);
            $('#amount').text(amount.toLocaleString('fr-FR'));
        }
    }
</script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-lg-3 col-md-5">
            <div class="row">
                <div class="col-12 bill-recap">
                    <div class="row">
                        <div class="col-12">
                            <p class="logo text-center logo-bill">Symbnb</p>
                        </div>
                        <div class="col-6 divider-bill">Numéro</div>
                        <div class="col-6 divider-bill strong-text">{{booking.id}}</div>
                        <div class="col-6 divider-bill">Date d'arrivée</div>
                        <div class="col-6 divider-bill strong-text">{{booking.startDate | date('d/m/y')}}</div>
                        <div class="col-6 divider-bill">Date de départ</div>
                        <div class="col-6 divider-bill strong-text">{{booking.endDate | date('d/m/y')}}</div>
                        <div class="col-6 divider-bill">Nombre de nuit</div>
                        <div class="col-6 divider-bill strong-text">{{booking.duration}}</div>
                        <div class="col-6 divider-bill">Montant total</div>
                        <div class="col-6 divider-bill strong-text">{{booking.amount}} &euro;</div>
                        <div class="col-12 bill-comment-title">Votre commentaire</div>
                        <div class="col-12 bill-comment">{% if booking.comment is null %}
                                Vous n'avez pas saisis de commentaire
                                {% else %}
                                {{booking.comment |striptags|slice(0,70)}} ...
                                {% endif %}</div>

                      
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-12"><img class="w-100" src="{{booking.ad.coverImage}}" alt=""></div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-5">
            <h2 class="alert-heading">Votre hôte</h2>
            <div class="row">
                <div class="col-3"><img class="rounded-circle w-75" src="{{booking.ad.author.picture}}" alt=""></div>
                <div class="col-9">
                    <h4>
                        <a href="{{ path('user_show', {'slug': booking.ad.author.slug}) }}">{{booking.ad.author.firstName}}</a>
                        <span class="badge badge-primary">
                            {{booking.ad.author.ads|length}} annonces
                        </span>
                        
                    </h4>
                    <p>
                        {{booking.ad.author.description|raw}}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-7">
            <h2 class="alert-heading">Votre hébergement</h2>
            <h4>
                <a href="{{ path('ads_show', {'slug': booking.ad.slug}) }}">{{booking.ad.title}}</a>
            </h4>
           
            {{booking.ad.content | raw}}
        </div>
    </div>
</div>

{% endblock %}